CC = gcc

CFLAGS = -Wall -Wextra -Wpedantic -g

SRC = main.c hash.c search.c query.c cleanup.c utils.c

TARGET = search_engine

all:
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)